import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Navbar } from "@/ui/navbar";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ justifyContent: "center", display: "flex" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Box width={825}>
          <Navbar />
          <main>{children}</main>
        </Box>
      </body>
    </html>
  );
}
